name = "MonadFunctions"
uuid = "19d5bc74-bed4-4bd0-9587-1a66a6c9910f"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
